export const Cities = {
    Antwerp: 'Antwerp',
    Brussels: 'Brussels',
    Ghent: 'Ghent',
    Leuven: 'Leuven',
    Liege: 'Liege',
    Namur: 'Namur',
    Mons: 'Mons',
    Hasselt: 'Hasselt',
    Bruges: 'Bruges',
    Kortrijk: 'Kortrijk',
    Mechelen: 'Mechelen',
    Aalst: 'Aalst',
    Tournai: 'Tournai',
    Ostend: 'Ostend',
};
